
FileList=function(ktml,container,target_path,select_file,options){KTStorage.add(this);var list_id=this.id;this.ktml=ktml;this.container=container;if(typeof(this.container)=="string"){this.container=document.getElementById(this.container);}
this.div=document.getElementById("files_list");this.div.has_context_menu=true;this.tim=null;utility.dom.attachEvent(this.div,'onscroll',function(){window.clearTimeout(file_list.tim);file_list.tim=window.setTimeout('file_list.onscroll()',50);});utility.dom.attachEvent(this.div,'onclick',function(){if(file_list.cancelClick){file_list.cancelClick=false;return false;}
file_list.selectChild("",true);file_list.trigger_event("onitemdeselect");});if(typeof(target_path)=="undefined")target_path="/";Object_weave_safe(this,options);this.path="";this.last_requested_path="";this.status=0;this.children=[];this.selection=[];if(typeof(window[this.type+"FileList"])!="undefined"){Object_weave(FileList.prototype,window[this.type+"FileList"].prototype);if(typeof(this.inittype)=="function"){this.inittype();}}
if(is.mozilla){window.addEventListener("DOMMouseScroll",function(e){file_list.onwheel(e);},true);}else{document.body.onmousewheel=function(e){file_list.onwheel(e);};}
select_file=select_file.replace(new RegExp("^.*\\/",""),"");this.list_path(target_path,this.filter,select_file);};FileList.prototype.onwheel=function(e){var o=utility.dom.setEventVars(e);utility.dom.stopEvent(o.e);var delta=is.ie?(o.e.wheelDelta>0?-1:+1):(o.e.detail>0?1:-1);delta*=137/2;this.div.scrollTop+=delta;if(is.mozilla){this.onscroll();}};FileList.prototype.onscroll=function(){window.clearTimeout(this.tim);this.tim=null;var st=this.div.scrollTop;var ot,i;for(i=0;i<this.children.length;i++){if(!this.children[i].revealed){ot=this.children[i].table.offsetTop;if((ot<st+274+137)&&(ot>st-137)){this.children[i].img.src=this.children[i].img.getAttribute("late_image");this.children[i].revealed=true;}}}};FileList.prototype.file_exists=function(file_name){return this.get_item(file_name);};FileList.prototype.trigger_event=function(event_name){var evfn;var args=[];for(var i=1;i<arguments.length;i++){args.push(FileList.prototype.trigger_event.arguments[i]);}
evfn=this[event_name];if(typeof(evfn)=="function"){evfn.apply(this,args);}};FileList.toggle_item=function(elem,e){var i,el,item,o,idx,minIdx=100000,maxIdx=-1,startIdx,endIdx;single=true;el=elem;while(el.tagName.toLowerCase()!="body"&&typeof(el.item_id)=="undefined"){el=el.parentNode;}
if(typeof(el.item_id)!="undefined"){item=KTStorage.get(el.item_id);if(e.ctrlKey&&!e.shiftKey){single=false;}
var list=KTStorage.get(item.list_id);if(e.shiftKey){idx=list.getChildIndexByName(item.name);for(i=0;i<list.children.length;i++){if(!list.children[i].selected){continue;}
minIdx=Math.min(minIdx,i);maxIdx=Math.max(maxIdx,i);}
list.deselectAll();startIdx=Math.min(idx,idx>maxIdx?maxIdx:idx);endIdx=Math.max(idx,idx<minIdx?minIdx:maxIdx);for(i=startIdx;i<=endIdx;i++){list.children[i].select(endIdx==startIdx,endIdx>startIdx);}
if(endIdx>startIdx){list.trigger_event("onitemselect",list.children[i-1].name)}}else{if(e.ctrlKey&&item.selected){item.deselect();if(list.children.length==1){list.trigger_event("onitemselect",list.children[0].name)}}else{list.selectChild(item.name,single);}}}
utility.dom.stopEvent(e);};FileList.prototype.list_path=function(target_path,filter,select_file,block){var list_id=this.id;if(typeof(filter)=="undefined"||filter=="")filter=this.filter;if(typeof(target_path)=="undefined"||target_path=="")target_path=this.path;this.last_requested_path=target_path;if(this.path!=target_path||this.filter!=filter){this.filter=filter;this.status=0;this.children=[];this.selection=[];if(FLS){document.body.appendChild(FLS);}
this.div.innerHTML='<div class="loading">'+trans(i18n.LOADING_FILES)+'</div>';var params={folder:target_path,submode:browse_submode,what:"files",filter:this.filter};this.ktml.makeRequest("folder","read",params,function(result){if(typeof(result)=='object'&&result.error){alert(result.error.message);return;}
KTStorage.get(list_id).receive_path(result,target_path,function(){if(KTStorage.get(list_id).tim==null||is.mozilla){KTStorage.get(list_id).onscroll();}
KTStorage.get(list_id).selectChild(select_file);if(typeof(block)=="function")block();});});}};FileList.prototype.receive_path=function(result,target_path,block){if(this.last_requested_path!=target_path){return;}
this.path=target_path;if(this.children.length==0){this.div.innerHTML=trans(i18n.NO_FILES);}
for(i=0;i<result.length;i++){this.addChild(result[i].name,result[i]);}
this.trigger_event("onload",target_path,result);if(typeof(block)=="function")block();if(FLS){this.div.appendChild(FLS);}};FileList.prototype.upload=function(result,block){};FileList.prototype.get_item=function(name){var idx;idx=this.getChildIndexByName(name);if(idx>=0){return this.children[idx];}
return false;};FileList.prototype.del=function(files,block){var i,dir,file;if(typeof(files)=="string")files=[files];files_left_to_delete=files.length;files_deleted=[];for(i=0;i<files.length;i++){dir=files[i].replace(new RegExp("[^\\/]+$",""),"");file=files[i].replace(new RegExp("^.*\\/",""),"");this.ktml.makeRequest("file","delete",{"submode":browse_submode,"filename":dir+file},function(result){files_deleted.push(result);if(typeof(result)=='object'&&result.error){alert(result.error.message);return;}
if(files_deleted.length==files_left_to_delete){block();}});}};FileList.prototype.before_op=function(files,block){this.opfiles=files;this.optoreceive=files.length;this.opreceived=0;this.operr=[];this.opblock=block;utility.window.blockInterface();};FileList.prototype.op=function(op,files,destdir,block){var srcdir;var list_id=this.id;if(typeof(destdir)=="undefined"||destdir=="")destdir=this.path;if(typeof(files)=="string")files=[files];srcdir=files[0].replace(/[^\/]+$/,"");if(op=="cut"&&srcdir==destdir){block([]);return;}
this.ktml.makeRequest("folder","read",{"folder":destdir,"submode":browse_submode,"what":"files","filter":browse_filter},function(result){if(typeof result=='object'&&result.error){alert(result.error.message);return;}
var names,newnames,i,cnt;var filename,tmpsrc,tmpdest;names=[];newnames=[];for(i=0;i<result.length;i++){names.push(result[i].name);}
Array_each(files,function(file){filename=file.replace(new RegExp("^.*\\/",""),"");newname=filename;cnt=1;while(Array_indexOf(names,newname)!=-1||Array_indexOf(newnames,newname)!=-1){newname="Copy "+(cnt>1?"("+cnt+") ":"")+"of "+filename;cnt++;}
newnames.push(newname);});var list=KTStorage.get(list_id);list.before_op(files,block);for(i=0;i<files.length;i++){tmpsrc=files[i];tmpdest=destdir;list.op_one(op,tmpsrc,tmpdest,function(result,s,d){list.op_receive(result,s,d);});}});};FileList.prototype.op_one=function(op,filename,newname,block){var was_cut=false;if(op=="cut"){op="copy";was_cut=true;}
ktml.makeRequest("file",op,{"filename":filename,"submode":browse_submode,"new_filefolder":newname},function(op_result){if(typeof(op_result)=='object'&&op_result.error){if(typeof block=="function")block(op_result,filename,newname);return;}
if(was_cut){ktml.makeRequest("file","delete",{"submode":browse_submode,"filename":filename},function(delete_result){if(typeof block=="function")block(op_result,filename,newname);});}else{if(typeof block=="function")block(op_result,filename,newname);}});};FileList.prototype.op_receive=function(result,src,dest){var i,s,tmp;this.opreceived++;if(typeof result=='object'&&result.error){this.operr.push({"message":result.error.message,"file":src});}
if(this.opreceived==this.optoreceive){utility.window.unblockInterface();if(typeof this.opblock=="function")this.opblock(this.operr);}};FileList.prototype.markforcut=function(item,replacemarks){var items=[],crt;if(typeof replacemarks=="undefined")replacemarks=false;if(typeof item=="string"){items.push(item);}else{items=item;}
if(typeof items=="object"&&items.length){for(i=0;i<this.children.length;i++){crt=this.children[i];if(Array_indexOf(items,crt.name)!=-1||Array_indexOf(items,crt.path)!=-1){crt.markforcut();}else if(replacemarks){crt.unmarkforcut();}}}};FileList.prototype.selectAll=function(){for(i=0;i<this.children.length;i++){var was_selected=this.children[i].selected;if(!was_selected){this.children[i].select(false,true);this.trigger_event("onitemselect",this.children[i].name,true);}}
if(this.children.length){this.trigger_event("onitemselect",this.children[i-1].name)}};FileList.prototype.deselectAll=function(){this.selectChild("",true,true);this.trigger_event("onitemdeselect","")};FileList.prototype.selectChild=function(name,single,silent){if(typeof single=="undefined")single=false;if(typeof silent=="undefined")silent=false;var i;if(single){for(i=0;i<this.children.length;i++){if(name!=this.children[i].name){this.children[i].deselect(true);}}}
for(i=0;i<this.children.length;i++){if(name==this.children[i].name){var was_selected=this.children[i].selected;this.children[i].select(single,silent);if(was_selected){this.trigger_event("onitemselect",name,silent);}}}};FileList.prototype.getChildIndexByName=function(name){var i;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){return i;}}
return-1;};FileList.prototype.addChild=function(name,result){var i,tmp,added,new_child,newnoext,crtnoext;tmp=this.div;if(this.children.length==0){tmp.innerHTML="";}
new_child=new FileListItem(this,result);newnoext=name.replace(/\.[^.]*$/,"").toLowerCase();for(i=0;i<this.children.length;i++){crtnoext=this.children[i].name.replace(/\.[^.]*$/,"").toLowerCase();if(newnoext<crtnoext){this.children.splice(i,0,new_child);tmp.insertBefore(new_child.div,this.children[i+1].div);added=true;break;}}
if(!added){this.children.push(new_child);tmp.appendChild(new_child.div);}
return new_child;};FileList.prototype.removeChild=function(name){var i,tmp;name=name.replace(new RegExp("^.*\\/",""),"");tmp=this.div;for(i=0;i<this.children.length;i++){if(name==this.children[i].name){tmp.removeChild(this.children[i].div);this.children.splice(i,1);if(this.children.length==0){this.div.innerHTML=trans(i18n.NO_FILES);;}
return;}}};FileList.prototype.replaceChild=function(){};FileList.prototype.refreshChild=function(){};FileList.prototype.dispose=function(){for(i=0;i<this.children.length;i++){file_list.children[i].dispose();}};FilesFileList=function(){};FilesFileList.prototype.inittype=function(){};FileListItem=function(list,result){var image,table;this.selected=false;this.markedforcut=false;this.list_id=list.id;this.name=result.name;this.path=list.path+result.name;if(list.type=="Files"){if(isImage(this.name)){this.type="Image";}else{this.type="File";}}
if(typeof window[this.type+"FileListItem"]!="undefined"){Object_weave(FileListItem.prototype,window[this.type+"FileListItem"].prototype);if(typeof this.inittype=="function"){this.inittype(result);}}};FileListItem.prototype.setDetails=function(result){var s="";for(var i in result){s+=i+": "+result[i]+"\n";}
alert(s)};FileListItem.prototype.update=function(result){if(typeof result=='object'&&result.error){alert(userFriendlyErr(result.error.message));return;}
var title=this.name;if(this.thumbnail){this.width=parseInt(result.width);this.height=parseInt(result.height);var scale=scaleDimensions(this.width,this.height);this.img.width=scale.width;this.img.height=scale.height;title+='\n'+trans(i18n.DIMENSIONS)+' '+this.width+' x '+this.height;}
this.size=parseInt(result.size);title+='\n'+trans(i18n.SIZE)+' '+showFriendlySize(this.size);this.table.title=title;KT_Tooltips.attach_single(this.table);};FileListItem.prototype.select=function(doscroll,silent){var idx,scrollto;if(typeof(doscroll)=="undefined"){doscroll=true;}
if(typeof(silent)=="undefined"){silent=false;}
item_selection_type="file";if(!this.selected){this.selected=true;utility.dom.classNameAdd(this.div,"thumbnail_selected");KTStorage.get(this.list_id).trigger_event("onitemselect",this.name,silent);}
if(doscroll){idx=KTStorage.get(this.list_id).getChildIndexByName(this.name);var item_height=this.table.offsetHeight+(is.ie?4:0);var st=KTStorage.get(this.list_id).div.scrollTop;scrollto=Math.floor(idx/4)*item_height;if(st+2*item_height<scrollto+item_height){KTStorage.get(this.list_id).div.scrollTop=scrollto-item_height;if(is.mozilla){KTStorage.get(this.list_id).onscroll()}}
if(st>scrollto){KTStorage.get(this.list_id).div.scrollTop=scrollto;if(is.mozilla){KTStorage.get(this.list_id).onscroll()}}}};FileListItem.prototype.deselect=function(silent){if(this.selected){this.selected=false;utility.dom.classNameRemove(this.div,"thumbnail_selected");KTStorage.get(this.list_id).trigger_event("onitemdeselect",this.name,silent);item_selection_type="none";}};FileListItem.prototype.markforcut=function(){if(!this.markedforcut){this.markedforcut=true;utility.dom.classNameAdd(this.div,"thumbnail_cut");}};FileListItem.prototype.unmarkforcut=function(){if(this.markedforcut){this.markedforcut=false;utility.dom.classNameRemove(this.div,"thumbnail_cut");}};FileListItem.prototype.setName=function(){};FileListItem.prototype.refreshThumbnail=function(){};FileListItem.prototype.dispose=function(){this.img=null;this.table=null;this.div=null;};function scaleDimensions(width,height){var ret={width:0,height:0};var ratio=width/height;var w=width;var h=height;if(w>100||h>100){if(w>h){w=100;h=parseInt(w/ratio);}else{h=100;w=parseInt(h*ratio);}}
ret.width=w;ret.height=h;return ret;};FileFileListItem=function(){};FileFileListItem.prototype.inittype=function(result){KTStorage.add(this);var image,tmp,href='javascript:;';this.revealed=false;this.size=result.size;if(result.thumbnail!="ERROR"){this.thumbnail=result.thumbnail;}else{this.thumbnail="img/unknown.gif";}
image='';tmp=KTStorage.get(this.list_id).ktml.getModuleProperty(browse_submode,'UploadFolderUrl');image+=tmp;this.width=parseInt(result.width);this.height=parseInt(result.height);var img_dimensions='';var late_image='';if(this.thumbnail){var scale=scaleDimensions(this.width,this.height);img_dimensions=' width="'+scale.width+'" height="'+scale.height+'" ';this.revealed=false;if(result.thumbnail=="ERROR"){image+=current_path+result.name;}else{image+=this.thumbnail;image+='?size='+this.size;}
late_image=image;image=window.topOpener.KtmlRoot+'core/img/s.gif';}else{this.revealed=true;if(this.name.match(/\.(avi|wmv|asf|txt|swf|mov|pdf)$/i)){var ext=RegExp.$1;if(ext=='wmv'||ext=='asf'){ext='avi';}
image=window.topOpener.KtmlRoot+'modules/filebrowser/img/'+ext+'.gif';}else{image=window.topOpener.KtmlRoot+'modules/filebrowser/img/unknown.gif';}}
this.div=document.createElement("span");this.div.item_id=this.id;this.div.has_context_menu=true;var cut_name=this.name;if(cut_name.length>13){var parts=cut_name.match(/(.*?)(\.?[^\.]*)$/);cut_name=parts[1].substring(0,12)+"..."+parts[2];}
this.div.innerHTML='\
  <table class="thumbnail_container" onclick="FileList.toggle_item(this, event)" ondblclick="FileList.toggle_item(this, event);insert_selected(this, event)">\
   <tr>\
    <td class="thumbnail_box"><img late_image="'+late_image+'" src="'+image+'" onmousedown="return false" '+img_dimensions+'/></td>\
   </tr>\
   <tr>\
    <td><div class="thumbnail_item_name"><span tabIndex="1" href="'+href+'">'+cut_name+'</span></div></td>\
   </tr>\
  </table>';this.table=this.div.getElementsByTagName('table')[0];this.img=this.div.getElementsByTagName("IMG")[0];};ImageFileListItem=function(){};ImageFileListItem.prototype.inittype=FileFileListItem.prototype.inittype;TemplateFileListItem=function(){};TemplateFileListItem.prototype.inittype=function(result){KTStorage.add(this);var image,tmp,href='javascript:;';this.size=result.size;var title=this.name;title+='\n'+trans(i18n.SIZE)+' '+showFriendlySize(this.size);image=window.topOpener.KtmlRoot+'modules/filebrowser/img/txt.gif';this.template_content=result.template_content;this.div=document.createElement("span");this.div.item_id=this.id;this.div.has_context_menu=true;this.revealed=true;this.div.innerHTML='\
  <table class="thumbnail_container" title="'+title+'" onclick="FileList.toggle_item(this, event)" ondblclick="FileList.toggle_item(this, event);insert_selected(this, event)">\
   <tr>\
    <td class="thumbnail_box"><div class="template_thumbnail">'+this.template_content+'</div></td>\
   </tr>\
   <tr>\
    <td><div class="thumbnail_item_name"><a href="'+href+'">'+this.name+'</a></div></td>\
   </tr>\
  </table>';this.table=this.div.getElementsByTagName('table')[0];};