
var help_mode=false;var status_message='';imageExtensions='gif,xbm,png,jpeg,jpg,jpe,jfif,tiff,tif,bmp';imageExtensionsRegExp=new RegExp("\\.(?:"+imageExtensions.split(",").join("|")+")$","i");movieExtensions='swf,mov,asf,wmv,mpeg,avi,mpg';movieExtensionsRegExp=new RegExp("\\.(?:"+movieExtensions.split(",").join("|")+")$","i");function isImage(fName){return browse_submode=="media"&&imageExtensionsRegExp.test(fName);};function isMovie(fName){return movieExtensionsRegExp.test(fName);};current_path="/";current_file="";current_selection=new PathsArray();item_selection_type="none";folder_tree=null;function update_current_path(src){var d;if(typeof(src)!="undefined"){if(src.indexOf("/")!=0){src="/"+src;}
current_path=src.replace(new RegExp("[^\\/]+$",""),"");current_file=src.replace(new RegExp("^\\/.*\\/",""),"");}};function setStatus(msg){window.defaultStatus=msg;window.status=msg;};i18n={};function trans(msg_id){if(opener){win=window.topOpener;}else{win=window;}
if(typeof(i18n[msg_id])=="undefined"){i18n[msg_id]=win.translate(msg_id);}
var s=i18n[msg_id];var args=[];args[0]=s;var exec='s = utility.string.sprintf(args[0]';for(var i=1;i<trans.arguments.length;i++){args[i]=trans.arguments[i];exec+=', args['+i+']';}
exec+=')';try{eval(exec);}catch(err){}
s=String_trim(s.replace(/\/r\/n/g,'\n'));return s;};if(typeof(KTStorage)=="undefined"){KTStorage=new ObjectStorage("ktml")}
var getvars=new QueryString();ktml=window.opener.ktmls[getvars.find('id')];browse_submode=ktml.getModuleProperty('filebrowser','browse_submode');browse_filter=ktml.getModuleProperty('filebrowser','browse_filter');browse_submode_detail=ktml.getModuleProperty('filebrowser','submodeDetail');currentUploadFolder=ktml.getModuleProperty(browse_submode,'UploadFolderUrl')
fileUploadFolder=ktml.getModuleProperty('file','UploadFolderUrl')
mediaUploadFolder=ktml.getModuleProperty('media','UploadFolderUrl')
function init(refresh){if(!window.opener){document.write("You do not have access directly to this area of the editor.");window.close();return;}
window.focus();if(typeof(refresh)=="undefined"){utility.window.setModal();}
if(typeof(refresh)=="undefined"){if(is.ie){document.charset=opener.document.charset;}
document.title=lang_translatepage("||Remote File Explorer||",ktml.config.UILanguage,window.opener);document.body.innerHTML=lang_translatepage(document.body.innerHTML,ktml.config.UILanguage,window.opener);set_i18n();}
setStatus(trans(i18n.DEFAULT_STATUS));var getvars,filter,selectedSrc,lastUsedFolder;if(typeof(refresh)=="undefined"){document.getElementById('file').style.display='';utility.dom.attachEvent(is.ie?document.body:document.documentElement,"onkeydown",keyboard_manager);init_selection();window.KtmlDirDepth=window.topOpener.KtmlDirDepth;window.KtmlRoot=window.topOpener.KtmlRoot;document.getElementsByTagName('form')[0].action=window.topOpener.KtmlAbsoluteServicePath;document.getElementById('id').value=ktml.id;submode_detail=ktml.getModuleProperty('filebrowser','submodeDetail');selectedSrc=ktml.getModuleProperty(browse_submode,'selectedSrc');lastUsedFolder=ktml.getModuleProperty(browse_submode,'lastUsedFolder');fileupload_change();fileBrowserType=ktml.getModuleProperty('filebrowser','fileBrowserType');if(!fileBrowserType||Array_indexOf(["image","media","file"],browse_submode)!=-1){fileBrowserType="Files";}
if(selectedSrc){update_current_path(selectedSrc);}else if(lastUsedFolder){update_current_path(lastUsedFolder);}
if(browse_submode=="templates"&&submode_detail=="saveas"){saveas_el=document.getElementById("template_saveas_name");saveas_el.focus();}}
set_buttons_state();fileupload_change();folder_tree=new FolderTree(ktml,"folders_list",current_path);file_list=new FileList(ktml,"files_container",current_path,current_file,{"filter":browse_filter,"type":fileBrowserType});folder_tree.onnodeselect=function(path){if(path!=current_path){update_current_path(path);setStatus(trans(i18n.LOADING_FOLDER,path));set_buttons_state();current_selection.removeAll();ktml.setModuleProperty(browse_submode,'lastUsedFolder',current_path.replace(new RegExp("^\\/",""),""));file_list.dispose();file_list.list_path(path,"","");}};file_list.onitemselect=function(lname,silent){if(typeof(silent)=="undefined"){silent=false;}
current_selection.add(current_path+lname);current_file=lname;if(!silent){if(current_selection.paths.length>1){status_message=trans(i18n.SELECTED_N_FILES,current_selection.paths.length);}else{status_message=trans(i18n.SELECTED_FILE,lname);}
setStatus(status_message);set_buttons_state();}};file_list.onitemdeselect=function(lname,silent){if(typeof(silent)=="undefined"){silent=false;}
current_selection.remove(current_path+lname);current_file="";if(current_selection.paths.length==1){current_file=current_selection.paths[0].replace(/(.*?)([^\/]*)$/,'$2')}
if(!silent){setStatus(current_selection.paths.length>1?trans(i18n.SELECTED_N_FILES,current_selection.paths.length):((current_selection.paths.length==1)?trans(i18n.SELECTED_FILE,current_file):trans(i18n.DEFAULT_STATUS)));set_buttons_state();}};file_list.onload=function(path,result){var node;node=folder_tree.path_to_node(path);if(!result.length){result.length=0;}
node.filteredfiles=result.length;var foldersCount=node.subfolders||0;var _statusStr=trans(i18n.FOLDER_CONTAINS,foldersCount,node.filteredfiles);window.setTimeout("setStatus('"+_statusStr+"')",100);node.setDetails({subfolders:foldersCount,allfiles:node.allfiles,filteredfiles:node.filteredfiles});if(typeof(global_response)!='undefined'&&global_response!=null&&global_response.length){var path=global_response;var lname=path.substr(path.lastIndexOf('/')+1,path.length);var item=file_list.get_item(lname);if(item){item.select();}
set_buttons_state();global_response=null;}};};function keyboard_manager(e){var o=utility.dom.setEventVars(e);var k=o.e.keyCode;if(",input,textarea,select,".indexOf(","+o.targ.tagName.toLowerCase()+",")>=0){return true;}
if(o.e.ctrlKey&&k==65){utility.dom.stopEvent(o.e);file_list.selectAll();window.setTimeout("document_clearselection()",0);}
if(k==46){delete_selected();}};function document_clearselection(){if(is.ie){document.selection.clear();}else{window.getSelection().removeAllRanges();}};function refresh2(){init(true);};function userFriendlyErr(result){var failedOperation=new RegExp("(blur)|(sharpen)|(contrast)|(brightness)","i");var noLibAvailable=new RegExp("(NO_LIB)|(imagemagick is required)","gi");if(noLibAvailable.test(result)){var operation=failedOperation.exec(result)?failedOperation.exec(result)[0].toLowerCase():'required';var template="The server does not own the needed libraries to perform the '%s' operation.";result=utility.string.sprintf(template,operation)+"\nIMAGE MAGICK is either not installed or not properly configured.";}
return result;};function gotopath(path){if(typeof(path)=="undefined"){path="/";}
if(path.lastIndexOf("/")!=path.length-1){path+="/";}
folder_tree.select_path(path);};function folder_new(){var nodeSelected=folder_tree.path_to_node(folder_tree.selected_path);if(nodeSelected.childrenStatus==0){nodeSelected.getChildren(function(){node.setOpen(1);createNewFolder()});return;}
if(nodeSelected.childrenStatus==3){createNewFolder();}};function createNewFolder(prevUserValue){var nodeSelected=folder_tree.path_to_node(folder_tree.selected_path);var userMsg;if(!prevUserValue){userMsg=trans(i18n.PLEASE_ENTER_NEW_FOLDER_NAME);}else if(nodeSelected.getChildIndexByName(prevUserValue)>=0){userMsg=trans(i18n.FOLDER_EXISTS);}
var newDefaultName=trans(i18n.DEFAULT_NEW_FOLDER_NAME);var uniqueSuffix=1;while(nodeSelected.getChildIndexByName(newDefaultName)>=0){uniqueSuffix++;newDefaultName=i18n.DEFAULT_NEW_FOLDER_NAME+' '+uniqueSuffix;}
newDefaultName=prevUserValue||newDefaultName;var newFolderName=(userMsg)?prompt(userMsg,newDefaultName):prevUserValue;if(newFolderName){while(newFolderName&&(!newFolderName.match(/^[^\x5c\x2f\x3a\x2a\x3f\x22\x3c\x3e\x7e\x7c\x27]+$/))){if(!newFolderName.match(/\w+/)){newFolderName='';}
newFolderName=prompt(trans(i18n.INVALID_FOLDER_NAME),newFolderName);if(newFolderName){newFolderName=newFolderName.replace(/\s{2,}/g,' ');newFolderName=String_trim(newFolderName);}}
if(nodeSelected.getChildIndexByName(newFolderName)>=0){newFolderName=prompt(trans(i18n.FOLDER_EXISTS),newFolderName);createNewFolder(newFolderName);return;}
if(newFolderName){utility.window.blockInterface();folder_tree.mkdir(newFolderName,function(){utility.window.unblockInterface();});}}}
var lastTopScroll=0;var preventQuickDeleteFlag=false;var deletionRequestRunning=false;function delete_selected(){if(deletionRequestRunning){return;}
var toDelete,confirm_str;if(current_path!="/"){toDelete=current_path;}
if(current_file!=""){toDelete=current_file;}
if(!toDelete){return;}
if(item_selection_type=="file"){}else if(item_selection_type=="folder"){}else{return;}
if(item_selection_type=='folder'){if(preventQuickDeleteFlag){return;}
var tmp=folder_tree.path_to_node(folder_tree.selected_path);var must_confirm=false;if(tmp.allfiles!=0||tmp.subfolders!=0){must_confirm=true;}
var ret=true;if(must_confirm){confirm_str=trans(i18n.CONFIRM_FOLDER_DELETE,tmp.subfolders,tmp.allfiles);ret=confirm(confirm_str);}
if(ret){deletionRequestRunning=true;folder_tree.rmdir("",function(){utility.window.unblockInterface();deletionRequestRunning=false;})}}else if(item_selection_type=='file'){if(current_selection.paths.length==0){return;}
confirm_str=trans(i18n.CONFIRM_FILE_DELETE,current_selection.paths.length);if(confirm(confirm_str)){preventQuickDeleteFlag=true;utility.window.blockInterface();lastTopScroll=document.getElementById('files_list').scrollTop;var path=current_selection.paths[0];var path=path.substr(0,path.lastIndexOf("/"));deletionRequestRunning=true;file_list.del(current_selection.paths,function(){for(var i=0;i<files_deleted.length;i++){file_list.removeChild(files_deleted[i]);}
files_deleted=[];current_selection.removeAll();current_file="";refresh2();utility.window.unblockInterface();deletionRequestRunning=false;var _execString="document.getElementById('files_list').scrollTop="+lastTopScroll+";"+"if(document.getElementById('files_list').scrollTop=="+lastTopScroll+"){window.clearInterval(RESET_SCROLL)}";RESET_SCROLL=window.setInterval(_execString,100);});}
set_buttons_state();}};function clickedSelected(){var fileToUpload=document.getElementById('file').value;if(fileToUpload==''){insert_selected();return false;}else{var uploadIframe=document.getElementById('uploadIframe');document.getElementById('module').value='file';document.getElementById('submode').value=browse_submode;document.getElementById('resize').value='false';document.getElementById('folder').value=current_path;document.getElementsByTagName('form')[0].submit();utility.window.blockInterface();file_list.deselectAll();utility.dom.addIframeLoad(uploadIframe,function(){utility.window.unblockInterface();var responseObj=uploadIframe.contentWindow.document.getElementsByTagName('textarea');var responseObj_id='';var responseObj_value='';if(responseObj&&responseObj.length){responseObj=responseObj[0];responseObj_id=responseObj.id;responseObj_value=responseObj.value;uploadIframe.onload=null;}else{uploadIframe.onload=null;return;}
if(responseObj_id=='error'){var response=eval('('+responseObj_value+')');alert(response.error.message);}else{global_response=responseObj_value;refresh2();}
fileupload_change(true);var fileToUploadControl=document.getElementById('file');fileToUploadControl.parentNode.innerHTML='<input name="Filedata" id="file" type="file" onchange="fileupload_change(false)" size="24" class="ktml_button" />';});return false;}};function insert_selected(){if(current_file==""){alert(trans(i18n.PLEASE_SELECT_SOMETHING));return;}
var callBackObject=ktml.getModuleProperty('filebrowser','callback');var obj=callBackObject[0];var func=callBackObject[1];var param=callBackObject[2];ktml.insert_count=current_selection.paths.length;for(i=0;i<current_selection.paths.length;i++){var fileName=current_selection.paths[i];fileName=fileName.replace(/^\x2f/,'');var fullFileName=window.topOpener.ktml_location.server+ktml.getModuleProperty(browse_submode,'UploadFolderUrl');fullFileName+=fileName;fullFileName+='?size='+file_list.get_item(current_file).size;if(browse_submode_detail=="forceurl"){obj[func](param,fullFileName);}else{obj[func](param,fullFileName,isImage(fileName),isMovie(fileName));}}
utility.window.hideModalBlocker(window.topOpener);utility.window.close();}
function clickedCancel(){utility.window.hideModalBlocker(window.topOpener);utility.window.close();}
function set_button_enabled(btn,state){if(state){utility.dom.classNameRemove(btn,'btn_disabled');}else{utility.dom.classNameAdd(btn,'btn_disabled');}}
function set_buttons_state(){var somethingIsSelected;var btn_home=document.getElementById('btn_home');set_button_enabled(btn_home,current_path!="/");somethingIsSelected=false;if(current_path!="/"||current_file!=""||current_selection.paths.length>0){somethingIsSelected=true;}
var btn_delete=document.getElementById('btn_delete');set_button_enabled(btn_delete,somethingIsSelected);var btn_new=document.getElementById('btn_new');set_button_enabled(btn_new,current_path=="/");multiple_selection=current_selection.paths.length!=1};function init_selection(){DNDDom.dhtml.setMovable("files_list",DND_HANDLE_FOR+"file_list_selection");FLS=document.getElementById("file_list_selection");var files_list_node=DNDDom.getElement("files_list");files_list_node.onStartMove=function(e,m){if(e.shiftKey){return false;}
if(m.target.parentNode.tagName=="BODY"){return false;}
m.FLBox=utility.dom.getBox(DNDDom.getElement("files_list"));m.scrollBarWidth=(m.source.offsetWidth-m.source.scrollWidth);if(m.FLBox.width+m.FLBox.x-m.scrollBarWidth<=e.clientX){return false;}
m.autoScrollAmount=7;m.autoScrollFactor=is.ie?10:3;m.target.style.width="0px";m.target.style.height="0px";m.currentX=m.startX=e.clientX-m.FLBox.x+document.getElementById("files_list").scrollLeft;m.currentY=m.startY=e.clientY-m.FLBox.y+document.getElementById("files_list").scrollTop;m.target.style.left=m.startX+"px";m.target.style.top=m.startY+"px";return true;};files_list_node.onMove=function(e,m){document_clearselection();if(m.FLBox.x>=e.clientX){m.currentX=0;}else if(m.FLBox.width+m.FLBox.x-m.scrollBarWidth<=e.clientX){m.currentX=m.FLBox.width-m.scrollBarWidth;}else{m.currentX=e.clientX-m.FLBox.x;}
if(m.FLBox.y>=e.clientY){DNDDom.mover.autoScrollAmount=parseInt((m.FLBox.y-e.clientY+2)/m.autoScrollFactor*2+5);window.clearInterval(m.interval2);m.interval2=null;if(!m.interval1){m.interval1=window.setInterval("file_list.div.scrollTop -= DNDDom.mover.autoScrollAmount; if(is.mozilla)file_list.onscroll();",60);}
m.currentY=0;}else if(m.FLBox.height+m.FLBox.y<=e.clientY-2){DNDDom.mover.autoScrollAmount=parseInt((e.clientY-2-m.FLBox.height-m.FLBox.y)/m.autoScrollFactor*2+7);m.currentY=m.FLBox.height-1;window.clearInterval(m.interval1);m.interval1=null;if(!m.interval2){m.interval2=window.setInterval("file_list.div.scrollTop += DNDDom.mover.autoScrollAmount; if(is.mozilla)file_list.onscroll();",60);}}else{DNDDom.mover.autoScrollAmount=7;window.clearInterval(m.interval1);m.interval1=null;window.clearInterval(m.interval2);m.interval2=null;m.currentY=e.clientY-m.FLBox.y;}
m.currentX+=document.getElementById("files_list").scrollLeft;m.currentY+=document.getElementById("files_list").scrollTop;var dx=m.currentX-m.startX;var dy=m.currentY-m.startY;if(m.target.style.display!="block"){if(Math.abs(dx)>4||Math.abs(dy)>4){m.target.style.display="block";}else{return;}}
if(dx>=2){m.target.style.left=(m.startX)+"px";m.target.style.width=(dx-2)+"px";}else if(dx==0){m.target.style.left=(m.startX)+"px";m.target.style.width=(0)+"px";}else if(dx==1){m.target.style.left=(m.startX)+"px";m.target.style.width=(0)+"px";}else if(dx==-1){m.target.style.left=(m.startX-1)+"px";m.target.style.width=(0)+"px";}else{m.target.style.left=(m.startX+dx)+"px";m.target.style.width=(-dx-1)+"px";}
if(dy>=2){m.target.style.top=(m.startY)+"px";m.target.style.height=(dy-2)+"px";}else if(dy==0){m.target.style.top=(m.startY)+"px";m.target.style.height=(0)+"px";}else if(dy==1){m.target.style.top=(m.startY)+"px";m.target.style.height=(0)+"px";}else if(dy==-1){m.target.style.top=(m.startY-1)+"px";m.target.style.height=(0)+"px";}else if(dy==-2){m.target.style.top=(m.startY-2)+"px";m.target.style.height=(1)+"px";}else{m.target.style.top=(m.startY+dy+0)+"px";m.target.style.height=(-dy-1)+"px";}};files_list_node.onEndMove=function(e,m){window.clearInterval(m.interval1);m.interval1=null;window.clearInterval(m.interval2);m.interval2=null;if(m.target.style.display=="none"){return true;}
m.target.style.display="none";if(!e.ctrlKey){file_list.deselectAll();}
file_list.cancelClick=true;var itemWidth=125;var itemHeight=137;var col1=parseInt(m.startX/itemWidth);var row1=parseInt(m.startY/itemHeight);var col2=parseInt(m.currentX/itemWidth);var row2=parseInt(m.currentY/itemHeight);var silent=!(row1==row2&&col1==col2);var sel_count;for(var i=Math.min(row1,row2);i<=Math.max(row1,row2);i++){for(var j=Math.min(col1,col2);j<=Math.max(col1,col2);j++){if((j+i*4)<file_list.children.length){file_list.children[j+i*4].select(!silent,silent);}}}
if(silent){setStatus(current_selection.paths.length?trans(i18n.SELECTED_N_FILES,current_selection.paths.length):trans(i18n.DEFAULT_STATUS));set_buttons_state();}};};function fileupload_change(forceSelect){var fileToUpload=document.getElementById('file').value;var button_label=((fileToUpload&&!forceSelect)?trans(i18n.BTN_UPLOAD):trans(i18n.BTN_SELECT));document.getElementById('upload_select').value=button_label;}
function showFriendlySize(size){size/=1024;var ret=parseInt(size);if(ret<1){ret=1;}
return ret+' KB';};function filter_files(){refresh2();};function set_i18n(){i18n.BTN_SAVE="Save";i18n.BTN_UPLOAD="Upload";i18n.BTN_SELECT="Insert";i18n.DEFAULT_STATUS="Remote File Explorer";i18n.LOADING_FOLDER="Loading folder:";i18n.SELECTED_N_FILES="Selected: %d files";i18n.SELECTED_FILE="Selected file: %s";i18n.FOLDER_CONTAINS="Folder contains: %s folder(s) and %s file(s).";i18n.LOADING="Loading...";i18n.LOADING_FILES="Please wait, generating thumbnails...";i18n.NO_FILES="No items that match the filter were found.";i18n.DIMENSIONS="Dimensions:";i18n.SIZE="Size:";i18n.PLEASE_SELECT_SOMETHING='Please select an image or file, then click the "Select" button to insert it into your document.';i18n.FILE_UPLOAD_ERRORS="The following errors have occured:\r\n%s";i18n.PLEASE_ENTER_NEW_FOLDER_NAME="Enter new folder name";i18n.DEFAULT_NEW_FOLDER_NAME="New Folder";i18n.INVALID_FOLDER_NAME="Folder name invalid";i18n.INVALID_FILE_NAME="File name invalid";i18n.FOLDER_EXISTS="Folder exists";i18n.CONFIRM_FILE_DELETE="Are you sure you want to delete %d selected file(s)?";i18n.CONFIRM_FOLDER_DELETE="Are you sure you want to delete the selected folder (%d subfolder(s), %d file(s))?";i18n.LBL_FILE_NAME="File name:";i18n.LBL_FILE_UPLOAD="File Upload:";i18n.NO_SELECTION="No selection!";i18n.RENAME_FILE="Rename file";i18n.RENAME_FOLDER="Rename folder";};function IEClean(){if(is.ie){if(folder_tree){try{folder_tree.dispose();}catch(err){}}
if(file_list){try{file_list.dispose();}catch(err){}
file_list.div=null;file_list.container=null;}}};